### ISSUE TITLE
Optimizing hyperparameters using several datasets

### ISSUE THREAD

**Issue by Paul-Charpentier** [iastro-pt/gpyrn#9]
Hello João ! Hello Team !

Wonderful work.

I just wanted to know how do you optimize the hyperparameters when using several datasets with MCMC or even with the default optimization when doing `gprn.optimize` ? I've tried to mimic the way it used to be with a single parameter but I didn't succeed.

Cheers !
Paul.

PS: I really think this could be very useful for my research so I will be very interested in having a discussion with you guys or even to collaborate.

**Comment by jdavidrcamacho** [comment]
Hi,

@j-faria might be more helpful in this than me
